### ISSUE TITLE
Redirect Problem using virtual shop urls

### ISSUE THREAD

**Issue by Tombro** [shopwareLabs/SwagBrowserLanguage#1]
Hey folks,
i have two shops, both with a virtual url - example.com/de-de/ and example.com/it-it/
When i go to the italian shop i get the redirect overlay which would like to redirect me to the german shop.

But when i click on accept and the redirect takes place i get this error message:

`Fatal error: Uncaught exception 'Enlight_Controller_Exception' with message 'Controller "it-it" not found'`

Regards,
Thomas

**Comment by teiling88** [comment]
Is it possible that in your config.php the parameter 
`'throwExceptions' => true,`
is set?

**Comment by mitelg** [comment]
Hi @Tombro 
is this still an issue with the newest version?

**Comment by mitelg** [comment]
closed due to inactivity. if this is still an issue for you, open a ticket again :blush: :+1:
