### ISSUE TITLE
Redirection page incorrect

### ISSUE THREAD

**Issue by thesplitter** [shopwareLabs/SwagBrowserLanguage#5]
I have installed the plugin, correctly configurated but when i select the correct language, i get redirected to the correct language but to an empty page with "Oops! An error has occurred!" title, the page is completely empty except for the "start page" button, the shop logo and the error text.

Shopware 5.2.7

Main shop + 2 Language shops

Activating the errors i get this:

ERROR
Message:
exception 'Shopware\Components\CSRFTokenValidationException' with message 'The provided X-CSRF-Token is invalid. Please go back, reload the page and try again.' in /usr/www/users/xxx/engine/Shopware/Components/CSRFTokenValidator.php:161
Stack trace:
0 [internal function]: Shopware\Components\CSRFTokenValidator->checkFrontendTokenValidation(Object(Enlight_Controller_ActionEventArgs))
1 /usr/www/users/xxx/engine/Library/Enlight/Event/Handler/Default.php(91): call_user_func(Array, Object(Enlight_Controller_ActionEventArgs))
2 /usr/www/users/xxx/engine/Library/Enlight/Event/EventManager.php(214): Enlight_Event_Handler_Default->execute(Object(Enlight_Controller_ActionEventArgs))
3 /usr/www/users/xxx/engine/Library/Enlight/Controller/Action.php(143): Enlight_Event_EventManager->notify('Enlight_Control...', Object(Enlight_Controller_ActionEventArgs))
4 /usr/www/users/xxx/engine/Library/Enlight/Controller/Dispatcher/Default.php(523): Enlight_Controller_Action->dispatch('indexAction')
5 /usr/www/users/xxx/engine/Library/Enlight/Controller/Front.php(223): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))
6 /usr/www/users/xxx/engine/Shopware/Kernel.php(177): Enlight_Controller_Front->dispatch()
7 /usr/www/users/xxx/vendor/symfony/http-kernel/HttpCache/HttpCache.php(487): Shopware\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
8 /usr/www/users/xxx/engine/Shopware/Components/HttpCache/AppCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true, NULL)
9 /usr/www/users/xxx/vendor/symfony/http-kernel/HttpCache/HttpCache.php(258): Shopware\Components\HttpCache\AppCache->forward(Object(Symfony\Component\HttpFoundation\Request), true)
10 /usr/www/users/xxx/vendor/symfony/http-kernel/HttpCache/HttpCache.php(275): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true)
11 /usr/www/users/xxx/engine/Shopware/Components/HttpCache/AppCache.php(133): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true)
12 /usr/www/users/xxx/vendor/symfony/http-kernel/HttpCache/HttpCache.php(206): Shopware\Components\HttpCache\AppCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true)
13 /usr/www/users/xxx/engine/Shopware/Components/HttpCache/AppCache.php(114): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
14 /usr/www/users/xxx/shopware.php(113): Shopware\Components\HttpCache\AppCache->handle(Object(Symfony\Component\HttpFoundation\Request))
15 {main}

Time:
2016-11-15T09:30:14.472847+0100

Channel:
core

request:
{
"uri": "/",
"method": "POST",
"query": [],
"post": {
"__shop": "6"
}
}

session:
No session data available

shopId:
6

shopName:
Italiano

**Comment by thesplitter** [comment]
I had to disable the CSRF Protection in the Frontend in order to make the plugin work

**Comment by mitelg** [comment]
Hi @thesplitter
 is this still an issue with the newest version?

**Comment by mitelg** [comment]
closed due to inactivity. if this is still an issue for you, open a ticket again :blush: :+1:
